name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        project: [web, api]

    defaults:
      run:
        working-directory: ${{ matrix.project }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint
        run: npm run lint -- --no-error-on-unmatched-pattern
        
      - name: Build
        run: npm run build
        
      - name: Test
        run: npm run test